name: iSponsorBlockTV
options:
  bundleIdPrefix: com.elchin91
  deploymentTarget:
    iOS: 14.0
configs:
  Debug: debug
  Release: release
targets:
  iSponsorBlockTV:
    type: application
    platform: iOS
    sources:
      - iSponsorBlockTV
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.elchin91.isponsorblockTV
      PRODUCT_NAME: iSponsorBlockTV
      CODE_SIGN_STYLE: Manual
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGN_IDENTITY: ""
      DEVELOPMENT_TEAM: ""
      PROVISIONING_PROFILE_SPECIFIER: ""
      INFOPLIST_FILE: iSponsorBlockTV/Info.plist
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      TARGETED_DEVICE_FAMILY: "1,2"
      SWIFT_VERSION: 5.0
      ENABLE_BITCODE: NO
      VALID_ARCHS: "arm64"
      ARCHS: "arm64"
      ONLY_ACTIVE_ARCH: NO
      EXCLUDED_ARCHS[sdk=iphonesimulator*]: "arm64"
      STRIP_SWIFT_SYMBOLS: NO
      COPY_PHASE_STRIP: NO
      ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES: YES
    settings:
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_COMPILATION_MODE: "incremental"
        Release:
          SWIFT_OPTIMIZATION_LEVEL: "-O"
          SWIFT_COMPILATION_MODE: "wholemodule"
schemes:
  iSponsorBlockTV:
    build:
      targets:
        iSponsorBlockTV: all
    run:
      config: Debug
    archive:
      config: Release 